name: Pipeline1
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Hello World
