name: Pipeline2
on:
  workflow_dispatch:
jobs:
  Stage_1:
    name: Stage 1
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Result from Stage 1
  Stage_2:
    name: Stage 2
    runs-on: ubuntu-latest
    needs: Stage_1
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Result from Stage 2
  Stage_3:
    name: Stage 3
    runs-on: ubuntu-latest
    needs: Stage_2
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Result from Stage 3
