name: Pipeline3
on:
  workflow_dispatch:
jobs:
  Building_and_Deploying_nginx:
    name: Building and Deploying nginx
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             sh 'sudo rm -rf Jenkins*'
#                                 sh 'git clone https://github.com/sreeharsha-alluri/Jenkins-to-GitHub.git'
#                                 sh 'sudo docker build -t my-nginx-image -f ~/workspace/Pipeline3/Jenkins-to-GitHub/Dockerfile .'
#                                 sh 'sudo docker run -td -p 8084:80 my-nginx-image'
